# Generated by Django 5.2.8 on 2025-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_url', models.URLField()),
                ('event_type', models.CharField(choices=[('import.completed', 'Import completed'), ('product.created', 'Product created'), ('product.updated', 'Product updated')], max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_response_ms', models.FloatField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
