# Generated by Django 5.2.8 on 2025-11-20 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='active',
            new_name='is_enabled',
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_response_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.CharField(choices=[('import.completed', 'Import completed'), ('product.created', 'Product created'), ('product.updated', 'Product updated')], max_length=64),
        ),
    ]
