# Generated by Django 5.2.8 on 2025-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='file_name',
        ),
        migrations.AddField(
            model_name='importjob',
            name='file_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='processed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('parsing', 'Parsing'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='total_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
