# Generated by Django 5.2.8 on 2025-11-20 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # Drop the table to avoid bigint to uuid casting issue
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS products_product CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update state: remove old model
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Product'),
            ],
        ),
        # Recreate model with UUID id and all fields including sku_norm
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('sku_norm', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
